### ISSUE TITLE
[Week3]

### ISSUE THREAD

**Issue by jingwen007** [Lidemy/mentor-program-3rd-jingwen007#19]
老師好：

抱歉，上傳有些問題
檔案上傳後，Compare & pull request 卻不見了
所以我按了有Marge.... 的按鈕

然後又更新目錄的檔案，再上傳
結果還是一樣沒出現Compare & pull request 
所以沒網址能複製，
請教老師這種情況接下來要怎辦呢？
為什麼它沒出現

**Comment by aszx87410** [comment]
因為你用的是同一個 branch，然後那個 branch 已經 merge 了所以不會出現
沒關係 我直接在之前那個上面改就好
